### ISSUE TITLE
Bug 回报：hexo默认配置highlight.enable为undefined导致代码高亮不启用

### ISSUE THREAD

**Issue by jht3QAQ** [jht3QAQ/Kratos-Rebirth#3]
### 报告前须知

- [X] 我确认该 Bug 是可复现的，我会根据下面的模板提供完整详尽的复现步骤
- [X] 我确认已认真阅读 ReadMe.md 和 文档，确认描述的内容有误或是不能解决我的问题
- [X] 我已知晓如果没有认真阅读且勾选这里所有的条目，或是没有使用此模板认真详细地描述问题，是对彼此时间的浪费，我的 issue 可能会被无解释关闭

### 安装方式

Git clone 项目仓库至 themes 目录下

### 对 Bug 的描述

在head.ejs中会检查config.highlight.enable是否为true  
而hexo默认配置没有设置此项导致代码高亮没有启用

### 复现的方法

![Snipaste_2023-12-31_15-42-07](https://github.com/jht3QAQ/Kratos-Rebirth/assets/25195987/ab3b2cd5-933b-4a79-a926-4cbf45922d34)

### 期望的行为

![Snipaste_2023-12-31_15-42-32](https://github.com/jht3QAQ/Kratos-Rebirth/assets/25195987/57acfe7e-c154-4104-8bb3-20c734832e3a)

### 运行环境

1df398c5a3d0aa112aff1649a2d98e0898664f84

### 主题配置文件

```yaml
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
```
